#!/usr/bin/env python3

#Generate a start script from templates that fills in specific values from config.yml.
#Execute this using the created Locker Docker image, e.g.:
#Run like this for maclinux: docker run --rm docker.rdcloud.bms.com:443/rr:locker_opensource /locker/gen_start_script maclinux > /tmp/start_script.sh
#Run like this for win: docker run --rm docker.rdcloud.bms.com:443/rr:locker_opensource /locker/gen_start_script win > /tmp/start_script.bat
#Note: run just like this, don't do --it or --tty as those might cause special characters to get inserted that will cause the generated script to not be able to be executed

import sys
import re
from Config import Config
import string
import unicodedata
import utils
import os

# Load locker configuration
config = Config("/config.yml")

platform = sys.argv[1]; #win or maclinux

if platform == 'win':
    template = '/locker/start_locker_win_template.bat'
elif platform == 'maclinux':
    template = '/locker/start_locker_template.sh'
else:
    raise Exception("Error: options are 'win' or 'maclinux'")

template_f = open(template, "r", encoding="utf-8")
 
#read whole file to a string
template_contents = template_f.read()
 
#close file
template_f.close()

# Substitute variables in template from config/environment.

#Note for platform == 'win', only config.locker_image is required to be defined.
#for platform == 'maclinux', that and others are required
if utils.empty(config.locker_image):
    print("Error: please define a value for locker_image in configuration file.")
    sys.exit()
else:
    template_contents = re.sub(
        r'__LOCKER_IMAGE__',
        config.locker_image,
        template_contents
    )

if platform == 'maclinux':
    if utils.empty(config.usable_ports):
        print("Error: please define a value for usable_ports in configuration file.")
        sys.exit()
    else:
        template_contents = re.sub(
            r'__USABLE_PORTS__',
            config.usable_ports,
            template_contents
        )

if not utils.empty(config.checkCorpNetworkVPNServer):
    template_contents = re.sub(
        r'__CHECK_CORP_NETWORK_VPN_SERVER__',
        config.checkCorpNetworkVPNServer,
        template_contents
    )
else:
    template_contents = re.sub(
        r'__CHECK_CORP_NETWORK_VPN_SERVER__',
        "",
        template_contents
    )

if platform == 'maclinux':
    if utils.empty(config.containerUser):
        print("Error: please define a value for containerUser in configuration file.")
        sys.exit()
    else:
        template_contents = re.sub(
            r'__CONTAINER_USER__',
            config.containerUser, 
            template_contents
        )

if config.proxies:
    if not utils.empty(config.proxies["http_proxy"]):
        template_contents = re.sub(
            r'__http_proxy__',
            config.proxies["http_proxy"],
            template_contents
        )
    else:
        template_contents = re.sub(
            r'__http_proxy__',
            "",
            template_contents
        )

    if not utils.empty(config.proxies["https_proxy"]):
        template_contents = re.sub(
            r'__https_proxy__',
            config.proxies["https_proxy"],
            template_contents
        )
    else:
        template_contents = re.sub(
            r'__https_proxy__',
            "",
            template_contents
        )
    if not utils.empty(config.proxies["ftp_proxy"]):
        template_contents = re.sub(
            r'__ftp_proxy__',
            config.proxies["ftp_proxy"],
            template_contents
        )
    else:
        template_contents = re.sub(
            r'__ftp_proxy__',
            "",
            template_contents
        )
    if not utils.empty(config.proxies["no_proxy"]):
        template_contents = re.sub(
            r'__no_proxy__',
            config.proxies["no_proxy"],
            template_contents
        )
    else:
        template_contents = re.sub(
            r'__no_proxy__',
            "",
            template_contents
        )

print(template_contents)

